/// Flutter icons MyFlutterApp
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
library;
import 'package:flutter/widgets.dart';

class Customicons {
  Customicons._();

  static const _kFontFam = 'Customicons';
  static const String? _kFontPkg = null;

  static const IconData home = IconData(0xe994, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xeadb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music = IconData(0xf001, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
